[package]
name = "tokenize"
version.workspace = true
rust-version.workspace = true
readme.workspace = true
repository.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
unicode-segmentation = "1.12"

[lints]
workspace = true
